services:
  db:
    image: mysql:5.6
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'

  app:
    build: docker
    volumes:
      - ./blog:/var/www/html/
    depends_on:
      - db
    ports:
    - 80:80
